### ISSUE TITLE
ARM64 architecture

### ISSUE THREAD

**Issue by chdanielmueller** [nick-invision/ansible-role-macos-github-actions-runner#1]
Hi,

I noticed that the ansible role is downloading the x64 version of the actions runner.
But an arm64 version is available.
Is there a way to configure which version to load?

Thanks,
Daniel

**Comment by chdanielmueller** [comment]
Found a way.

```yaml
- name: Install GitHub Actions Runner
  hosts: macs
  user: ansible
  become: yes
  vars:
    - github_account: github-access-user
    - runner_org: true
  roles:
    - role: nick-invision.macos_github_actions_runner
    - github_actions_architecture: arm64
```
